### PR TITLE
Added quote header regex for Norwegian Gmail and tests for those

### PR DESCRIPTION
**Pull request by tsmes**
I added a quote header regex and tests so it works with Norwegian Gmail.

This should be a single commit, based on master.

### CODE REVIEW

**Comment by tsmes** [comment]
I'll rename the test fixture since somebody already has used that file name.

**Comment by tsmes** [comment]
It seems like it failed on composer install for PHP 7

**Comment by willdurand** [comment]
There is/was a packagist issue today.

**Comment by willdurand** [comment]
Thanks @tsmes, it is merged!

**Pull request merged**
