### PR TITLE
Fix quote header regexes

### PR DESCRIPTION
**Pull request by kipit**
Hello,

This PR fix the gluttony of some quote header regexes. ATM, the change has only been applied to English, French, Spanish and Italian headers.

### CODE REVIEW

**Comment by kipit** [comment]
Hi @willdurand,

We have added a test case which lead to a segfault in php-5.6 with the old quote header regex.
I’m still struggling with the Travis build… Right now, in this PR at least, HHVM build don't pass.

I've try some Travis variation in another PR https://github.com/willdurand/EmailReplyParser/pull/58 but without any success.

I'm stuck at that point, if someone has any idea, let me know ;-)

**Comment by willdurand** [comment]
Let's fix Travis-CI setup first, then we'll look into this PR. I am working on it :)

**Comment by willdurand** [comment]
@kipit sorry for having pushed into your own fork, but it looks like everything is back to stable, right? WDYT? Should I merge? Travis-CI does not get any fault in 5.6.

**Comment by kipit** [comment]
I've rebased my branch to your master, and squashed my commits to ease the merge. All tests passed, so, from my point of view, you can merge.

FYI: the segfault occure, only on php5, if you change the spanish regex from:
```php
/^\s*(El(?:(?!^>*\s*El\b|\bescribió:).){0,1000}escribió:)$/ms
```
to
```php
/^\s*(El(?:(?!^>*\s*El\b|\bescribió:).)*escribió:)$/ms
```
Finally, this is a small improvement cause, 1000 should be sufficient to grab a quote header on multiple lines.

**Comment by willdurand** [comment]
perfect, thanks!

**Pull request merged**
