### PR TITLE
Add quote header regex for Norwegian Gmail

### PR DESCRIPTION
**Pull request by tsmes**
I added a quote header regex and tests so it works with Norwegian Gmail.

### CODE REVIEW

**Comment by tsmes** [comment]
From what I can tell the reason it fails is because it can't autoload the 'PHPUnit_Framework_TestCase' class when running the tests on PHP 7.

**Comment by stof** [comment]
This is because Travis PHP 7 images now have PHPUnit 6 by default

**Comment by tsmes** [comment]
Ok, so either the Travis test routine needs to be reworked or some configuration needs to change. I guess that is out of my hands for now. :)

**Comment by willdurand** [comment]
Yeah, I guess we have to update the test suite..

**Comment by tsmes** [comment]
I tested it on my local system with php 7.1 and phpunit 5 and it passed.

**Comment by willdurand** [comment]
> I tested it on my local system with php 7.1 and phpunit 5 and it passed.

Yes, I think it is only a problem with the current project test suite.

**Comment by tsmes** [comment]
@willdurand I'm sorry for badgering you, but is it possible to get this merged and have a release pushed to packagist soon?

**Comment by willdurand** [comment]
Sure, but I have to fix the test suite first.. If you could give a hand on that, it would speed up things a lot and it would be super-nice ❤️

**Comment by willdurand** [comment]
@tsmes could you rebase your branch maybe?

**Comment by tsmes** [comment]
I think I did it correctly. I'm not that well versed in Github and pull requests.

**Comment by willdurand** [comment]
@tsmes looks good to me. do you think you would be able to squash your commits?

http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by tsmes** [comment]
You know what? I think I've messed up everything about the history of that branch. Since it's only a couple of changes I'll redo it in a new branch/pull request. :)

**Pull request closed without merging**
