### PR TITLE
Add addQuoteHeadersRegex function

### PR DESCRIPTION
**Pull request by tomsommer**
To add custom regexp during runtime

### CODE REVIEW

**Comment by willdurand** [comment]
There is a setter that has been introduced for that..

**Comment by tomsommer** [comment]
The setter overrides the entire array, this adds an entry.

**Comment by amakhrov** [comment]
@tomsommer Can't itbe done by getting the whole array (using the getter), appending an entry, and setting the array (via the setter)? This won't require any  interface change, and covers more cases (e.g removing a regex from the list)

**Comment by tomsommer** [comment]
Good idea, don't know why I didn't think of that.

**Pull request closed without merging**
