### PR TITLE
Add Github Action, remove travis

### PR DESCRIPTION
**Pull request by barryvdh**
Github actions should probably be enabled on the repo.

### CODE REVIEW

**Comment by barryvdh** [comment]
I also normalized the line endings to LF instead of CRLF.

**Comment by willdurand** [comment]
I fixed CI in https://github.com/willdurand/EmailReplyParser/pull/88

**Comment by barryvdh** [comment]
Thanks! Not sure what is up with my line endings.

**Comment by willdurand** [comment]
Yeah, it is a bit odd.

**Pull request closed without merging**
