### PR TITLE
make SIG_REGEXP forward way

### PR DESCRIPTION
**Pull request by glensc**
more understandable if you need to debug something

mentioned here:
https://github.com/willdurand/EmailReplyParser/pull/42#issuecomment-184572081

ps: tests pass!

### CODE REVIEW

**Comment by willdurand** [comment]
haha, cool! thank you

**Comment by glensc** [comment]
oh, seems i forgot  to mention it also tries to add the "official" signature pattern: `^-- `
however as the parser is line based it's closest as it can get (should be really `^-- \n`)

**Comment by stof** [comment]
@glensc testing the end of line would mean anchoring the end of the regex too: ``^-- $``

**Comment by glensc** [comment]
@stof right, sent another PR

**Pull request merged**
